sources:
  var_log:
    type: file
    include:
      - /var/log/*
    exclude:
      - /var/log/*.gz
      - /var/log/falcon*
      - /var/log/wtmp
    sink: var-log-to-ngsiem
    transforms:
      - type: static_fields
        fields:
          organization.name: name of the organization here in the format: client-company-name (i.e company-name or john-doe-and-sons)
  var_log_auditd:
    type: file
    include:
      - /var/log/audit/*.log
    sink: auditd-to-ngsiem
    transforms:
      - type: static_fields
        fields:
          organization.name: name of the organization here in the format: client-company-name (i.e company-name or john-doe-and-sons)
sinks:
  var-log-to-ngsiem:
    type: hec
    token: "REPLACE_WITH_SINK_API_TOKEN"
    url: REPLACE_WITH_SINK_ENDPOINT_URL"
    workers: 4
    compression: gzip
    compressionLevel: 9
    maxEventSize: 910000
    maxBatchSize: 12000000
  auditd-to-ngsiem:
    type: hec
    token: "REPLACE_WITH_SINK_API_TOKEN"
    url: REPLACE_WITH_SINK_ENDPOINT_URL"
    workers: 4
    compression: gzip
    compressionLevel: 9
    maxEventSize: 910000
    maxBatchSize: 12000000
